### ISSUE TITLE
The project "bank2ynab" already knows the format for ING NL 

### ISSUE THREAD

**Issue by torbengb** [kurt-stolle/ynab-ing-parser#1]
Hello Kurt!
I've seen that you added a new YNAB repository to GitHub. Have you seen that there are already many similar projects? There is one in particular that could be very interesting for you: "bank2ynab"

https://github.com/torbengb/bank2ynab/blob/develop/README.md

If you could provide a sample CSV export (anonymized) then we could easily create the converter for your bank. We are nearly done with ING NL anyway, so your help would be fantastic: https://github.com/torbengb/bank2ynab/issues/91

Let me know what you think! 
Best regards from snowy Austria,
Ben

**Comment by khwstolle** [comment]
Hi Ben,

Since I created this repository, I have already created a parser that works for my needs. The main upside being that I can parse payments that match a certain rule into a format that makes more sense to me personally (e.g. grouping payees under different names, making certain common descriptions more readable). 

I can however provide you with the CSV format I have found ING Bank to be using, so that you may use this in your project. Here you go: 
[anonymized.csv.txt](https://github.com/kurt-stolle/ynab-ing-parser/files/1740346/anonymized.csv.txt)


Kind regards,
Kurt

**Comment by torbengb** [comment]
Wonderful, thank you very much for this file! Could you also tell me what the bank's default filename is when you download a CSV file? We could use that to identify the format for the conversion.

Glad you have good use from your personalized solution, that sounds nice.
Cheers,
Ben

**Comment by khwstolle** [comment]
The default filename is the IBAN followed by the range of dates that export covers. An export of 2018-02-05 until and including 2018-02-20 would have the format ``NLxxINGBxxxxxxxxx_05_02_2018_19_02_2018.csv`` where an 'x' denotes an integer value of in the IBAN.

**Comment by torbengb** [comment]
Awesome, thank you so much!
